# SME Cash Flow Prediction Configuration

# Data paths
data_dir: "datasets"
model_dir: "models"
output_dir: "outputs"

# Model parameters
training:
  random_state: 42
  test_size: 0.2
  validation_split_date: "2015-07-01"
  
# Feature engineering
features:
  lag_days: [1, 7, 14, 30]
  rolling_windows: [7, 14, 30]
  
# Prediction parameters
prediction:
  forecast_horizons: [30, 60, 90]
  confidence_interval: 0.95
  
# API settings
api:
  host: "0.0.0.0"
  port: 8000
  reload: true
  
# Visualization
visualization:
  figsize: [14, 8]
  dpi: 600

